#!/bin/sh -f

# clones visilibity (one cpp and hpp) from github,
# builds some test/application(s) using it,
# and runs them.


set -exo pipefail


dir=$1
if [ "$dir" == "" ]; then
  echo "Missing arg(s)."
  exit 1
fi
if [ ! -e $dir ]; then
  git clone https://github.com/karlobermeyer/VisiLibity1.git ./$dir
      # Remember git commit inside $dir will use this repo,
      # not the repo I defined a few directories up.
fi
cd $dir
cd ./src


#make clean 2>&1 | tee make_clean.log
    # doesn't work
make 2>&1 | tee make.log
make main 2>&1 | tee make_main.log

cp example1.environment surroundings.txt
head -2 example1.guards > guards.txt
./main ./surroundings.txt ./guards.txt \
  2>&1 | tee \
  ./main.log


